Numpy array operation

In [1]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print ("Basic slicing",arr[2:8])
print("with step:",arr[1:7:2])
print("Negative index:",arr[-4])

Basic slicing [3 4 5 6 7 8]
with step: [2 4 6]
Negative index: 6


In [11]:

arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("spesific element:",arr_2d[1,2])
print("entire row:",arr_2d[1])
print("entire column:",arr_2d[:,1])

spesific element: 6
entire row: [4 5 6]
entire column: [2 5 8]


In [13]:
unsorted = np.array([12,3,4,8,9,10])
print("sorted array",np.sort(unsorted))

arr_2d_unsorted = np.array([[1,3],[4,2],[5,7]])
print("sorted matrix:",np.sort(arr_2d_unsorted, axis=0))

sorted array [ 3  4  8  9 10 12]
sorted matrix: [[1 2]
 [4 3]
 [5 7]]


filter

In [ ]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10,11,12,14])
even_number = numbers[numbers % 2 == 0]
print("even number",even_number)


even number [ 2  4  6  8 10 12 14]
numbers greater than 5 [ 6  7  8  9 10 11 12 14]


filter with mask

In [17]:
mask = numbers > 5
print("numbers greater than 5", numbers[mask])

numbers greater than 5 [ 6  7  8  9 10 11 12 14]


fansy indexing vs np.where()


In [21]:
indices = [0,2,5]
print(numbers[indices])
where_result = np.where(numbers > 5)
print(where_result)
print("np where", numbers[where_result])

[1 3 6]
(array([ 5,  6,  7,  8,  9, 10, 11, 12]),)
np where [ 6  7  8  9 10 11 12 14]


condition array

In [23]:
condition_array = np.where(numbers > 5,numbers*4,"false")
print(condition_array)

['false' 'false' 'false' 'false' 'false' '24' '28' '32' '36' '40' '44'
 '48' '56']


adding and removing data

In [24]:
arr1 = ([1,2,3,4,5])
arr2 = ([6,7,8,9,10])
combine = np.concatenate((arr1,arr2))
print(combine)

[ 1  2  3  4  5  6  7  8  9 10]


array compatibility

In [27]:
a = np.array([1,2,3])
b = np.array([4,5,6,7])
c = np.array([8,9,10])
print("compactibility shapes:",a.shape == b.shape) 
print("compactibility shapes:",a.shape == c.shape) 

compactibility shapes: False
compactibility shapes: True


In [34]:
original = np.array([[1,2],[3,4]])
new_raw = np.array([5,6])
with_new_raw = np.vstack((original,new_raw))
print(original)
print(with_new_raw)
new_col = np.array([[7],[8]])
with_new_col = np.hstack((original,new_col))
print(with_new_col)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 7]
 [3 4 8]]
