##numpy arry and basic


In [1]:
import numpy as np

creating array from list


In [19]:
my_list = [1,2,3,4]
print("python list multiplication",my_list * 2)

np_array = np.array([1,2,3,4]) #element wise multiplication
print("python list multiplication",np_array * 2)

import time
start = time.time()
my_list = [i*2 for i in range(100000)]
print("\n list operation time :", time.time() - start)

start = time.time()
np_array = [i*2 for i in range(100000)]
print("\n numpy operation time :", time.time() - start)



python list multiplication [1, 2, 3, 4, 1, 2, 3, 4]
python list multiplication [2 4 6 8]

 list operation time : 0.0042879581451416016

 numpy operation time : 0.0031228065490722656


creating array from scratch

In [27]:
zeros = np.zeros((2,3))
print("\n zeros:",zeros)

ones = np.ones((5,6))
print("\n ones:",ones)

full = np.full((2,5),9)
print("\n full:",full)

random = np.random.random((3,5))
print("\n random:",random)

sequence = np.arange(0,15,2)
print("\n sequence p:",sequence)


 zeros: [[0. 0. 0.]
 [0. 0. 0.]]

 ones: [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]

 full: [[9 9 9 9 9]
 [9 9 9 9 9]]

 random: [[0.06774704 0.23115739 0.41235936 0.18956154 0.33000599]
 [0.41043665 0.96923591 0.06813307 0.31863682 0.07784911]
 [0.15833867 0.77478064 0.86560886 0.84750174 0.66262752]]

 sequence p: [ 0  2  4  6  8 10 12 14]


In [1]:

import numpy as np
arr = np.arange(12)
print("original:",arr)
reshaped = arr.reshape((3,4))
print("\n Resheped",reshaped)

flattened = reshaped.flatten()
print("\n flattened array:",flattened)
#ravel(return views , insted of copy)
raveled = reshaped.ravel()
print("\n raveled array",raveled)



original: [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Resheped [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 flattened array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array [ 0  1  2  3  4  5  6  7  8  9 10 11]
